const testBoard = [
  [
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
  ],
  [
    { ...defaultCell, containsMine: true },
    { ...defaultCell },
    { ...defaultCell, containsMine: true },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
  ],
  [
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell, containsMine: true },
    { ...defaultCell },
  ],
  [
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell, containsMine: true },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
  ],
  [
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
  ],
  [
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
    { ...defaultCell },
  ],
];
